### PR TITLE
cmake.build: installation fixed

### PR DESCRIPTION
**Pull request by artiomn**

### CODE REVIEW

**Comment by kiplingw** [comment]
@Tachi107, are you fine with this?

**Comment by Tachi107** [comment]
As with #1044, we purposely removed the install target from CMake because new users are encouraged to use Meson to install the project. It provides a richer install target, with a pkg-config file (that everybody should use to consume the dependency, avoiding fragmentation with CMake package exports and whatnot), SONAME versioning, possibility to easily install shared libraries, static, or both, etc.

I'm not against re adding CMake installation support if there's a good reason for it, but I can't think of any ("I just want to use CMake" is not a valid reason).

@artiomn (and @soeroesg), if you have a valid reason for this, please let us know. I might be missing something.

But if you simply want to install pistache without having to deal with Meson too much just type `pip install meson ninja`, `meson setup build`, `meson install -C build` (of course you can, and probably should, replace `pip install` with your system's package manager, like `apt install meson`) .

**Comment by artiomn** [comment]
CMake is the de facto standard. But of course, I tried Meson build first.
Meson doesn't install the library correctly. I have this with a CMake build (with pkgconfig): 

```
[100%] Linking CXX executable ../../bin/phistache-example-server
cd /usr/src/gb/build/l5/phistache-example && /usr/bin/cmake -E cmake_link_script CMakeFiles/phistache-example-server.dir/link.txt --verbose=1
/usr/local/bin/g++ -g CMakeFiles/phistache-example-server.dir/server.cpp.o -o ../../bin/phistache-example-server  -lpthread 
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `main':
/usr/src/gb/src/l5/phistache-example/server.cpp:27: undefined reference to `Pistache::Http::Endpoint::options()'
/usr/bin/ld: /usr/src/gb/src/l5/phistache-example/server.cpp:27: undefined reference to `Pistache::Port::Port(unsigned short)'
/usr/bin/ld: /usr/src/gb/src/l5/phistache-example/server.cpp:27: undefined reference to `Pistache::IP::any()'
/usr/bin/ld: /usr/src/gb/src/l5/phistache-example/server.cpp:27: undefined reference to `Pistache::Address::Address(Pistache::IP, Pistache::Port)'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `Pistache::Async::Promise<long> Pistache::Http::ResponseWriter::send<14ul>(Pistache::Http::Code, char const (&) [14ul], Pistache::Http::Mime::MediaType const&)':
/usr/local/include/pistache/http.h:429: undefined reference to `Pistache::Http::ResponseWriter::sendImpl(Pistache::Http::Code, char const*, unsigned long, Pistache::Http::Mime::MediaType const&)'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `Pistache::Http::Endpoint::~Endpoint()':
/usr/local/include/pistache/endpoint.h:25: undefined reference to `Pistache::Tcp::Listener::~Listener()'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `void Pistache::Http::listenAndServe<HelloHandler>(Pistache::Address, Pistache::Http::Endpoint::Options const&)':
/usr/local/include/pistache/endpoint.h:211: undefined reference to `Pistache::Http::Endpoint::Endpoint(Pistache::Address const&)'
/usr/bin/ld: /usr/local/include/pistache/endpoint.h:212: undefined reference to `Pistache::Http::Endpoint::init(Pistache::Http::Endpoint::Options const&)'
/usr/bin/ld: /usr/local/include/pistache/endpoint.h:213: undefined reference to `Pistache::Http::Endpoint::setHandler(std::shared_ptr<Pistache::Http::Handler> const&)'
/usr/bin/ld: /usr/local/include/pistache/endpoint.h:214: undefined reference to `Pistache::Http::Endpoint::serve()'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `Pistache::Tcp::Handler::Handler(Pistache::Tcp::Handler const&)':
/usr/local/include/pistache/tcp.h:41: undefined reference to `vtable for Pistache::Tcp::Handler'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `Pistache::Http::Handler::Handler(Pistache::Http::Handler const&)':
/usr/local/include/pistache/http.h:676: undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `Pistache::Http::Handler::~Handler()':
/usr/local/include/pistache/http.h:714: undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /usr/local/include/pistache/http.h:714: undefined reference to `Pistache::Tcp::Handler::~Handler()'
/usr/bin/ld: CMakeFiles/phistache-example-server.dir/server.cpp.o: in function `Pistache::Http::Handler::Handler()':
/usr/local/include/pistache/http.h:676: undefined reference to `Pistache::Tcp::Handler::Handler()'
/usr/bin/ld: /usr/local/include/pistache/http.h:676: undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /usr/local/include/pistache/http.h:676: undefined reference to `Pistache::Tcp::Handler::~Handler()'
```

**Comment by Tachi107** [comment]
That seems strange, and I believe that the issue is not related to Meson. Could you share the relevant CMakeLists.txt parts?

**Comment by artiomn** [comment]
> Could you share the relevant CMakeLists.txt parts?

100% copied from the library README.

**Comment by Tachi107** [comment]
When calling `target_link_libraries()` you should link to `PkgConfig::Pistache`, not `${Pistache_LIBRARIES}`

**Comment by Tachi107** [comment]
Looking again at https://github.com/pistacheio/pistache/pull/1046#issuecomment-1086396759 I noticed that the linking command does not pass the `-lpistache` argument, so you aren't linking against the installed Pistache library at all. (`g++ -g CMakeFiles/phistache-example-server.dir/server.cpp.o -o ../../bin/phistache-example-server  -lpthread` - notice that there's only `-lpthread`)
I don't know where, but there's definitely something wrong in your environment / CMake

**Comment by artiomn** [comment]
Yes, I see. Thank you for demonstration. I'll try to use Meson build again. But please understand: I don't fix what isn't broken. First, I checked my build.
Of course, I followed your instructions (and used PkgConfig::Pistache to link). But the build failed.

I'll rebuild the image using Meson to build Pistache and then write to you.

**Comment by Tachi107** [comment]
> Possible. But the environment in the Docker image is "clean and transparent". Another possibly variant is that your build environment has some old files or tweaks.

Yes, it had an old version of Pistache installed on the system, but I've retested this in a clean Debian VM and linking still works (if you link to `PkgConfig::Pistache`)

Maybe you're environment is "too clean", i.e. it misses some required packages (make sure you install either `pkg-config` or `pkgconf`)

**Comment by artiomn** [comment]
> Maybe you're environment is "too clean", i.e. it misses some required packages (make sure you install either pkg-config or pkgconf)

No, all required packages have been installed. Otherwise, the Pistache build would fail.

But I've tested with Meson build again. All works.
I thing the problem was in the forgotten `ldconfig` call.

**Comment by Tachi107** [comment]
> But I've tested with Meson build again. All works.

Happy to hear that :)

**Pull request closed without merging**
