### PR TITLE
#842: Add more debug traces to http server test

### PR DESCRIPTION
**Pull request by hyperxor**
More traces for issue #842 investigation

### CODE REVIEW

**Comment by kiplingw** [comment]
@dennisjenkins75 or @oktal, you ok with this? This has been ongoing for a long time, but the areas he's patched I'm no expert in.

**Comment by kiplingw** [comment]
@hyperxor, maybe something you can help explain to me. The call to ::shutdown(fd_, SHUT_RDWR) should prevent any future use on the socket. But why would there be any after the client has closed the connection?

**Comment by hyperxor** [comment]
@kiplingw I have re-read tutorials about sockets again and I decided to remove `::shutdown(fd_, SHUT_RDWR);` change. It seems it won't help to fix problem in test.

**Comment by kiplingw** [comment]
You are a wise man! Shall I keep this PR open for the time being while you tinker further?

**Comment by hyperxor** [comment]
@kiplingw It would be better to merge this PR to master. It will help me to analyze problem.

**Comment by kiplingw** [comment]
Good idea. I'll let you know as soon as I see another similar failure by the Launchpad build bot.

**Comment by hyperxor** [comment]
@kiplingw thank you so much

**Comment by kiplingw** [comment]
No problem. Your idea of adding more tracing is a good one for the time being.

**Comment by kiplingw** [comment]
@hyperxor, you got lucky (lol), it broke just now building for s390x. Build log is available [here](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+build/21375991/+files/buildlog_ubuntu-groovy-s390x.pistache_0.0.002-202104092244~ubuntu20.10.1_BUILDING.txt.gz). It looks like all of your tracing was successfully logged.

**Comment by kiplingw** [comment]
And again just now in focal for armhf. Build log is available [here](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+build/21380316/+files/buildlog_ubuntu-focal-armhf.pistache_0.0.002-202104102232~ubuntu20.04.1_BUILDING.txt.gz).

**Comment by Tachi107** [comment]
Also Travis reports test failures for the HTTP client, see [here](https://travis-ci.org/github/pistacheio/pistache/jobs/766565105#L3939)

**Comment by hyperxor** [comment]
@kiplingw Hello, I have created yet another PR #901. Please, can you send me again a link to broken build with these changes.

**Comment by kiplingw** [comment]
Sure @hyperxor. I merged your additional tracing. You can find two recent build failures captured [here](https://github.com/pistacheio/pistache/issues/842#issuecomment-818315814) and [here](https://github.com/pistacheio/pistache/issues/842#issuecomment-818926360). They are from Launchpad and local builds respectively.

I recommend trying @jacobbogdanov's pending #859 PR. His migration to `std::optional` and other minor changes seems to have, at least on my machine, affected the thread scheduler just enough to make the above race condition now a 100 % reproducible on my machine in [autopkgtest](https://github.com/pistacheio/pistache/#autopkgtest).

**Pull request merged**
