### PR TITLE
build: Meson options for custom OpenSSL lib/hdr path

### PR DESCRIPTION
**Pull request by win32asm**
Required in case the openssl library is not native to the build environment (e.g. part of vcpkg fetched dependencies).

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @win32asm. Can you also remember to [document](https://github.com/pistacheio/pistache/blob/master/README.md#building-from-source) the proposed new build flags in our `README.md`?

**Review by kiplingw — APPROVED** [review]

**Comment by kiplingw** [comment]
I'm fine with it. @dennisjenkins75, @Tachi107?

**Comment by Tachi107** [comment]
I'm not a fan of this workaround. Can't you simply override the pkg-config search directories to include your custom OpenSSL build?

**Comment by win32asm** [comment]
> I'm not a fan of this workaround. Can't you simply override the pkg-config search directories to include your custom OpenSSL build?

Let us see if we can use a pkg-config-based detection way.

**Comment by kiplingw** [comment]
> I'm not a fan of this workaround. Can't you simply override the pkg-config search directories to include your custom OpenSSL build?

That's actually a really good point.

**Comment by Tachi107** [comment]
Nice to hear! Happy to help :)

**Pull request closed without merging**
