### PR TITLE
allow compiling on darwin

### PR DESCRIPTION
**Pull request by mavrukin**
allow building on 'darwin' and not just on 'linux'

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @mavrukin. But my guess is you will probably need to make a lot more changes than this to get the library to build on OS X. Have you tried successfully?

**Comment by Tachi107** [comment]
This is not possible, see #1, #41, #183, #760, #960, #985

**Comment by mavrukin** [comment]
Sadly, doesn't look like it will work

**Comment by barracuda156** [comment]
@Tachi107 This is perhaps a strong statement. It should be possible, just needs to be fixed.

**Comment by Tachi107** [comment]
> @Tachi107 This is perhaps a strong statement. It should be possible, just needs to be fixed.

Yeah of course, nothing is impossible, but _someone_ has to do the work. Patches are always welcome if you want to help :)

**Pull request closed without merging**
