### PR TITLE
CMake subproject fixes

### PR DESCRIPTION
**Pull request by Tachi107**
In this PR I've made some minor improvements to the CMake files so that Pistache plays more nicely when it is included as a subproject. See the individual commits for details.

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @Tachi107. I'm fine with it, notwithstanding the two CI failures on: `NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer`. We can merge now and fix that later, if you like, since that's not really anything to do with your PR.

**Comment by Tachi107** [comment]
Il giorno ven 19 ago 2022 alle 08:21:35 -07:00:00, Kip 
***@***.***> ha scritto:
> Thanks @Tachi107. I'm fine with it, notwithstanding the two CI 
> failures on: NOTICE: You are using Python 3.6 which is EOL. Starting 
> with v0.62.0, Meson will require Python 3.7 or newer. We can merge 
> now and fix that later, if you like, since that's not really anything 
> to do with your PR.
> 

The Python 3.6 notice isn't actually the cause of the failure, which is 
explained a few lines above:

   meson.build:5:0: ERROR: Compiler clang++ can not compile programs.

I've fixed this in #1092, thanks for merging both!

-- 
OpenPGP key: 66DE F152 8299 0C21 99EF  A801 A8A1 28A8 AB1C EE49

**Comment by Tachi107** [comment]
@patrick-kings, could you check if this fixes your issue with CMake FetchContent?

**Comment by patrick-kings** [comment]
Thank you so much, this works fine

**Comment by Tachi107** [comment]
Awesome, thanks for the feedback :D

**Pull request merged**
