### PR TITLE
Docusaurus migration

### LINKED ISSUE #862: GitHub Pages site points to the wrong branch
I think that [pistache.io](https://pistache.io) hosts the `gh-pages` branch of the repo, thus rendering useless changes to `index.html` in the main branch (commit 8f278dbd345b818740f865623d5039e9314352fd).
As a temporary solution, the GitHub Pages site should be built from the `master` branch, and the `gh-pages` one should be deleted. This is a GitHub setting, and I can't submit a pull request to fix it.
image

Looking at the site and the source, it seems that the web page was generated by Jekyll, but I can't find the Markdown(?) files used to generate it. In my opinion the ideal solution would be to have a CI/CD automatically generate html files from Markdown (or similar) files stored in a `web/` or in the `docs/` folder on every commit, and push those files to a `gh-pages` branch containing only the generated site sources.

### PR DESCRIPTION
**Pull request by Tachi107**
Following @oktal's request in https://github.com/pistacheio/pistache/issues/862#issuecomment-773547718, here's the pistache.io documentation site migrated to docusaurus.

Documentation files are contained in pistache.io/docs, and are in Markdown format. The files that I added contain almost the same things as in the "old" site. 

Sidebar elements can be changed by editing pistache.io/sidebars.js. 

The homepage contains a few [undraw](https://undraw.co) images and, again, almost the same things as the original site. Differently from the documentation files, this one is written in (i believe) JSX, that is JavaScript plus HTML templating for React, if I remember correctly, but it could be changed to a Markdown file if needed.

I also wrote a GitHub Actions file that automatically deploys the site using GitHub Pages. Works for me in [PwRAu/scraf-backend/.github/workflows/raml-gh-pages.yml](https://github.com/PwRAu/scraf-backend/blob/main/.github/workflows/raml-gh-pages.yml), and I think should also work for Pistache. If it doesn't, there's [a better way of doing this](https://v2.docusaurus.io/docs/deployment), but it requires access to the repo's settings. 

Another thing that I would like to enable but requires access to the repo's settings is [HTTPS](https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https).

In the docs I also mention that Pistache requires a C++17 compiler. I know that this is not (yet) true, but this should make the switch (#859) easier.

Needless to say, this would fix #862.

Some screenshots:
image

image

image

### CODE REVIEW

**Comment by oktal** [comment]
Dude, this is very, **very**, VERY, **VERY** cool !

This is something I wanted to do for a long time but was very lazy, and you nailed it !

Having a GitHub Action automatically deploying the site is very nice as well !

Do you think we should use the [pistache.github.io](https://github.com/pistacheio/pistache.github.io) repo to host the doc and site ?

**Comment by kiplingw** [comment]
Well done. Unless there are any objections, I will merge.

**Comment by Tachi107** [comment]
> Do you think we should use the [pistache.github.io](https://github.com/pistacheio/pistache.github.io) repo to host the doc and site ?

I prefer having everything in one place, so that when you modify the code you can also edit the documentation very easily. 

Oh, and I just noticed that Docusaurus does not "support" the `sh` language for syntax highlighting within markdown code fences (I should've written `shell` instead), and more importantly that I left a placeholder at the bottom of the page (`Copyright © 2021 Pistache. Built by Tachi with <3 and Docusaurus.`), what should I write there before merging?

Happy to help :)

**Comment by Tachi107** [comment]
Alright, I set the footer text to a more general "Pistache, 2015 - 2021" and fixed shell syntax highlighting. 
Ready to merge

**Comment by oktal** [comment]
I'm fine with that, @kiplingw @dennisjenkins75 ?

**Comment by Tachi107** [comment]
Oops, I just realised that I put the GitHub Actions file in the wrong directory (`.github/ISSUE_TEMPLATE/workflows/pistache.io.yaml` instead of `.github/workflows/pistache.io.yaml`) could somebody move the dir one level up please?

**Comment by Tachi107** [comment]
That file was automatically generated by Docusaurus, so I have no idea 🤷‍♂️️.

I've also seen that the GitHub action fails to install `yarnpkg` through apt... That's probably because `ubuntu-latest` still uses Ubuntu 18.04. Could you change `ubuntu-latest` to `ubuntu-20.04` in `.github/workflows/pistache.io.yaml`, line 11? I should've checked in advance, sorry :/

**Comment by kiplingw** [comment]
Done.

**Comment by Tachi107** [comment]
And it failed again.
```shell
Unpacking npm (6.14.4+ds-1ubuntu2) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-x0Pr48/330-yarnpkg_1.22.4-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.
```
I have **no idea** why apt fails to install a couple of packages, that doesn't make any sense

**Comment by kiplingw** [comment]
I don't know much about Yarn, but my experience has been that every time someone tries to create a new package manager they reinvent apt and much more poorly.

That error message is elusive. But the only thing I can think of that could have broken it is if the package has a `preinst` hook that broke.

**Pull request merged**
