### PR TITLE
Follow-up to #1052

### PR DESCRIPTION
**Pull request by Tachi107**

### CODE REVIEW

**Comment by Tachi107** [comment]
Now we'll see if this actually breaks Ubuntu builds :)

**Comment by kiplingw** [comment]
We shall see!

**Comment by kiplingw** [comment]
So for Jammy it builds, but it [fails to upload](https://code.launchpad.net/~pistache+team/+archive/ubuntu/unstable/+recipebuild/3349836) due to what looks like the versioning in the file name.

For the older Focal, it looks like we're going to have to drop support for it because its [missing](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+recipebuild/3349837) the debhelper-compat (= 13). That's not really critical though because we don't have an official stable release yet anyways so no need to support older releases.

**Comment by Tachi107** [comment]
> So for Jammy it builds, but it [fails to upload](https://code.launchpad.net/~pistache+team/+archive/ubuntu/unstable/+recipebuild/3349836) due to what looks like the versioning in the file name.

Yeah pushing multiple builds in the same day isn't really supported by the classic `+git<date>.<hash>` format

> For the older Focal, it looks like we're going to have to drop support for it because its [missing](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+recipebuild/3349837) the debhelper-compat (= 13). That's not really critical though because we don't have an official stable release yet anyways so no need to support older releases.

Oh I thought Focal did support dh 13, or that at least it got backported, being a supported release :/

**Comment by Tachi107** [comment]
> Oh I thought Focal did support dh 13, or that at least it got backported, being a supported release :/

And it is in fact supported in [focal-backports](https://packages.ubuntu.com/focal-backports/debhelper). Is it possible to build packages using backports in the PPA?

**Comment by kiplingw** [comment]
Good call. I've added backports to both the stable and unstable PPAs. Let me try rebuilding now for all. The upload failure we can ignore for now, but let's see if it at least builds. I've also added bionic just for shit kicks to see if it works.

**Comment by kiplingw** [comment]
Ok it looks like it's building for Jammy, Impish, and Focal - but not Bionic. That's ok. That's reasonable. Bionic is nearly half a decade old. There's still the upload error, but that should disappear when I try again tomorrow.

**Comment by Tachi107** [comment]
> Ok it looks like it's building for Jammy, Impish, and Focal - but not Bionic. That's ok. That's reasonable. Bionic is nearly half a decade old. There's still the upload error, but that should disappear when I try again tomorrow.

I think that's reasonable too. Could you link me the logs, please? I'm unable to find them

**Comment by kiplingw** [comment]
Weird. You should be getting the build failure logs emailed to you because you're on the Launchpad team.

As for logs and manually triggering a rebuild, try [here](https://code.launchpad.net/~pistache+team/+recipe/pistache-daily).

**Comment by Tachi107** [comment]
> Weird. You should be getting the build failure logs emailed to you because you're on the Launchpad team.

I believe I only get emailed about build failures related to daily automated builds and builds that I manually trigger. I seem to remember that you didn't receive a bunch of build failures that I manually triggered some months ago either

**Comment by kiplingw** [comment]
Yeah that would make sense.

**Comment by kiplingw** [comment]
Hey @Tachi107. I noticed from observing the CI failures in #1054 and #1040 that it looks like it is failing because we're still running them in Focal, but:

```
The following packages have unmet dependencies:
 builddeps:. : Depends: debhelper-compat (= 13)
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

I think you can bump the CI test bed to Jammy, since it's the new LTS. Once that's done, @IHni3 can rebase and I'll trigger CI to restart.

**Comment by Tachi107** [comment]
Actually I think that the CI doesn't need the build deps at all, as it 
only runs `dpkg-source --build` while the actual binary build is 
executed in the Debian Testing autopkgtest image. I'll submit a PR 
fixing it soon

**Pull request merged**
