### PR TITLE
fix #1194: Endpoint::Options::backlog_ not used

### LINKED ISSUE #1194: Endpoint::Options::backlog_ is not used
The Endpoint::Options struct has a member called "backlog_", this member is not passed down to listener::init(). As a result, the default argument in the method declaration is used, which is always 128.

### PR DESCRIPTION
**Pull request by jiankyu**
This commit passes down the Options::backlog_ in the following invocation: Http::Endpoint::init() -> Tcp::Listener::init()

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @jiankyu. You'll need to [update](https://github.com/pistacheio/pistache?tab=readme-ov-file#versioning) the versioning too. Otherwise it looks good.

**Comment by jiankyu** [comment]
Thanks @kiplingw for pointing this out. Updated the version, in my time zone it's Feb 23, hope it doesn't make a big deal.

**Comment by kiplingw** [comment]
LGTM. @Tachi107, if you're fine with it feel free to merge.

**Review by Tachi107 — APPROVED** [review]
Looks good to me too, thanks for the fix!

**Pull request merged**
