### PR TITLE
Fix several unnecessary copies of objects

### PR DESCRIPTION
**Pull request by hyperxor**
I have found several places in code with unnecessary copies of objects and fixing them in this PR.

### CODE REVIEW

**Comment by kiplingw** [comment]
@hyperxor, thanks for this PR. Until we get our Travis CI up and running again, can you please run your changes through autopkgtest, as described in the readme, and verify nothing you changed broke?

**Comment by kiplingw** [comment]
@dennisjenkins75, I'm not sure why a system that's been used millions of times by hundreds of thousands of packages is still a "thingy" to you. You've used that expression a number of times. I'm surprised you still haven't read up on it. Google and nearly everyone relies on DEP-8 CI testing every day. The solution is to have it properly integrated, which Travis CI doesn't do. When the package is accepted into Debian, then it will automatically go through CI testing but not for daily commits.

As it stands right now, putting aside the fact that we don't even have Travis CI anymore, even if we did, it's a terrible system. It's centralized, cannot test on different architectures, and requires its own ad hoc YAML descriptors rather than an internationally standardized format. 

For the time being, this is all we have. I don't see how running a single command to test thoroughly when all the tests are already setup is any more work than the work entailed in patching, compiling, and running.

**Comment by kiplingw** [comment]
Build is still [failing](https://launchpadlibrarian.net/508519009/buildlog_ubuntu-groovy-ppc64el.pistache_0.0.002-202011242302~ubuntu20.10.1_BUILDING.txt.gz) on ppc64el and all other architectures.

**Comment by hyperxor** [comment]
@kiplingw 
```
... can you please run your changes through autopkgtest, as described in the readme, and verify nothing you changed broke?
```
I will try to do it a little bit later because now I don't have enough free disk and ram memory on my virtual machine with Ubuntu (I will do it on the another machine).

```
Build is [still](https://launchpadlibrarian.net/508519009/buildlog_ubuntu-groovy-ppc64el.pistache_0.0.002-202011242302~ubuntu20.10.1_BUILDING.txt.gz) failing on ppc64el and all other architectures.
```
Is it caused by my changes and there were the same problems before?

**Comment by kiplingw** [comment]
Don't know. It's hard to say since Dennis and I aren't exactly sure when Travis CI broke, so anyone's PR since then is as good a candidate as any.

**Comment by hyperxor** [comment]
@kiplingw @dennisjenkins75 I have checked [logs](842) of failed builds and it's this #842 issue, not related to my changes. I think this PR can be merged.

**Pull request merged**
