### PR TITLE
make filesystem compatible with gcc7.5.0 and gcc >=8

### PR DESCRIPTION
**Pull request by zydxhs**
This is a follow up to #1061, use has_include instead of ifdef

### CODE REVIEW

**Comment by Tachi107** [comment]
Hi @zydxhs, thanks for reopening this! We've reverted #1061, so as you can see this PR has conflicts. Could you please rebase on the latest master?

I usually use the following commands:

    git remote add upstream https://github.com/pistacheio/pistache.git
    git fetch upstream
    git rebase upstream/master

**Comment by zydxhs** [comment]
@Tachi107  I've done it now.

**Comment by kiplingw** [comment]
@zydxhs, it looks like you are having a CI failure on linux / linux (registry.access.redhat.com/ubi8/ubi-minimal, clang, none). Looks harmless, but you should take a look. Once all CI has passed, if @Tachi107 is fine with it, we will merge.

**Comment by zydxhs** [comment]
@kiplingw There is still one CI failure, but I don't know why and how to resolve it. It seems like it depends on the compilation environment?

**Comment by kiplingw** [comment]
I was actually wondering that myself. This might be something only @Tachi107 can solve. It looks like it's a dependency problem with a deprecated version of the Python runtime.

**Comment by Tachi107** [comment]
Yes, it seems that RHEL 8 broke their clang package recently. I've also encountered this issue in another software I maintain that has a similar CI environment.

I haven't investigated the issue yet, but it is not related to this PR in particular.

Anyway, I'll review this soon

**Comment by kiplingw** [comment]
@Tachi107, if you can rebase, re-trigger CI, and verify everything passes, you can go ahead and merge when ready.

**Comment by Tachi107** [comment]
I'm looking at the diff right now

**Comment by kiplingw** [comment]
Nice work again @Tachi107.

**Comment by Tachi107** [comment]
Thanks, @zydxhs!

I'll re-merge the changes you previously submitted in the master branch as soon as possible (or you can submit yet-another pull request if you prefer)

**Pull request merged**
