### PR TITLE
make headers incasesensitive

### PR DESCRIPTION
**Pull request by stevijo**
Headers are not case sensitive

### CODE REVIEW

**Comment by nelsonhf** [comment]
I would prefer you named the comparison function caseInsensitiveCompare...
Maybe also create a function findCaseInsensitive that would encapsulate all 3 calls to make the code easier to understand. I tried to do it but it seems my C++ is not that good (I had a problem with pointers and references).
Except for that, I tested it and it solves issue #86.

**Comment by stevijo** [comment]
After looking at it again ist would probably also be better to just save all headers lower case/ upper case and then just use a transform before using find. Because iterating over the unordererd map is not particulary fast.

**Comment by nelsonhf** [comment]
On the other hand, you'll almost never have more than 10-15 headers so optimizing may not be very important.

One problem with modifying the headers before saving is that debugging may be harder. But you'd detect the case where a request is sent with the same header in different cases.

I figured out how to make the function I was talking about:

```
std::unordered_map<std::string, Registry::RegistryFunc >::iterator
Registry::findCaseInsensitive(const std::string& name)
{
    return std::find_if(registry.begin(),registry.end(),[&](const std::pair<std::string,Registry::RegistryFunc>& header) {
        return incasesensitiveCompare(name,header.first);
    });
}
```
Then your Registry functions would look like

```
std::unique_ptr<Header>
Registry::makeHeader(const std::string& name) {
    auto it = findCaseInsensitive(name);
    if (it == std::end(registry)) {
        throw std::runtime_error("Unknown header");
    }

    return it->second();
}

bool
Registry::isRegistered(const std::string& name) {
    return findCaseInsensitive(name) != std::end(registry);
}
```

Something similar may be done for `Collection::remove()` but I'm not sure it would be any improvement

**Comment by xoac** [comment]
this can now be closed. This was merged:
https://github.com/oktal/pistache/commit/54a373157f7bcdb4ceb3ddd6914bc6f587fd6b58

**Comment by Tachi107** [comment]
Fixed by https://github.com/pistacheio/pistache/commit/54a373157f7bcdb4ceb3ddd6914bc6f587fd6b58

**Pull request closed without merging**
