### PR TITLE
Fix server crash on client disconnection in transport.cc i.e. issue#1007.

### PR DESCRIPTION
**Pull request by amang8662**
Fixed issue #1007 of server crash on client disconnection.
https://github.com/pistacheio/pistache/issues/1007

### CODE REVIEW

**Comment by Tachi107** [comment]
Hi, thanks for your contribution :)
How/why does this fix #1007?

**Comment by amang8662** [comment]
Hi @Tachi107 , the issue was that send() API used for data transfer generated SIGPIPE signal in case client got disconnected. To resolve it, I have passed a flag MSG_NOSIGNAL to it. Hence, now the API will return failure along with errno EPIPE which is being handled in Transport::asyncWriteImpl function line 304.

**Comment by Tachi107** [comment]
Looks like a good solution to me. Are you aware of any drawbacks? @kiplingw, @dennisjenkins75, if this looks good to you too it would be nice to merge this

**Comment by tn-jed** [comment]
Thanks @amang8662!

A few thoughts...
* I believe it'll be important to also detect that the pipe is broken (check for `errno == EPIPE` I think?) and then stop trying to send and do any cleanup. Otherwise, server will keep attempting and failing on the `send()` - could take a while if it was to be a big transfer.
* Took a quick look and this _seems_ to be the only usage of `::send()` - would be important that this fix is applied to all other instances

**Comment by kiplingw** [comment]
@amang8662, thanks for your PR. Could you add a unit test that demonstrates the old code breaking and verifies that your proposed fix works?

**Comment by amang8662** [comment]
@tn-jed, regarding the points you shared:
1. I checked whether we can stop further calls to send() by indicating user but haven't found any solution as of now. The changes I made ensures that system won't get crashed on disconnection and doesn't seem to impact any other workflows.
2. Changes at other API can be planned in future. Though, I don't think that affects current issue.

@kiplingw the replication steps described by @tn-jed  in #1007 can be considered as a testcase. We can execute and verify the same testcase with and without the fix.

**Comment by kiplingw** [comment]
Thanks, but it would still be preferable with a unit test in the actual tree.

**Comment by tn-jed** [comment]
@kiplingw see pr #1023 for a test case

**Comment by Tachi107** [comment]
It seems that this commit is not fixing the test failure introduced in #1023

**Comment by kiplingw** [comment]
Indeed @tn-jed. Looks like it still needs a bit of work (or possibly the unit test).

**Comment by jakob-stark** [comment]
@Tachi107 on my local machine, this fix makes the test #1023 pass.

**Comment by tn-jed** [comment]
@jakob-stark you're 100% right. I think this check is already done correctly and it's just the `EPIPE` that needs to be taken care of.

**Comment by Tachi107** [comment]
Hi, could you please rebase? The CI had an issue that made it test code in the master branch as opposed to these changes, but c3e740a11d9787ba2bf0d454386de424f2d7febc fixed it

**Comment by Tachi107** [comment]
This PR got closed as #1040 was merged instead

**Pull request closed without merging**
