### PR TITLE
ci(autopkgtest): install autopkgtest from Debian Testing

### PR DESCRIPTION
**Pull request by Tachi107**
Building it from source is not needed anymore

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @Tachi107. Hopefully this fixes the CI drama.

**Comment by Tachi107** [comment]
Unfortunately it won't, at least for now... But I'm looking for a more robust solution

**Comment by Tachi107** [comment]
Upstream bug related to our autopkgtest failures: [bugs.debian.org/1003002](https://bugs.debian.org/1003002)

**Comment by kiplingw** [comment]
Good eye @Tachi107.

**Pull request merged**
