### PR TITLE
Add unit test for #970

### PR DESCRIPTION
**Pull request by Tachi107**
The diff is quite big because I modified `new-certs.sh` to generate a new password-protected `.key` file, and re-running it updated the existing certs. I'm starting to think that those certs shouldn't be there anyway, as they are generated files and generated files should be produced at build time, but I'll do it in another PR.

Another "change" I made was renaming the test suite of the tests in `test/https_server_test.cc`, as it was mistakenly named "`http_client_test`". It is now called "`https_server_test`".

The unit test is quite basic, as the functionality to test is simple. It basically loads the password-encrypted key file and attempts a simple http request.

This must be merged after #970

### CODE REVIEW

**Comment by Tachi107** [comment]
Builds are failing because I based my patch on the [Ne02ptzero/pistache/work/louis/password_openssl](https://github.com/Ne02ptzero/pistache/tree/work/louis/password_openssl) branch, but since I'm not a Git wizard I don't know how to make an actual PR referencing that changes. 
As soon as #970 gets merged I can rebase and everything will be fine (I ran the tests locally)

**Comment by kiplingw** [comment]
@Tachi107, it looks good. Unless @dennisjenkins75 has any feedback, I am ready to merge.

**Comment by Tachi107** [comment]
Master is now broken. #970 must me merged as well

**Comment by kiplingw** [comment]
Done.

**Pull request merged**
